# These commands might be requred as JAVA might be using old keys
# sudo add-apt-repository ppa:webupd8team/y-ppa-manager
# sudo apt-get update
# sudo apt-get install y-ppa-manager

- name: install oracle java 8
  hosts: localhost
  gather_facts: yes

  tasks:
  - debug: msg="user={{ansible_user}}"

  - name: Install dependencies
    become: yes
    apt: name={{item}} state=latest
    with_items:
      - software-properties-common
      - dirmngr

  - name: Install add-apt-repostory
    become: yes
    apt: name=software-properties-common state=latest

  - name: Add Oracle Java Repository
    become: yes
    apt_repository:
      repo: deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main
      state: present

  - name: Add an apt key by id from a keyserver
    become: yes
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: EEA14886

  - name: Accept Java 8 License
    become: yes
    debconf: name='openjdk-8-jre-headless' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

  - name: update cache and ignore errors in case of problems
    become: yes
    apt: update_cache=yes
    ignore_errors: yes

  - name: purge java 8 installer - to avoid problems if installation is repeated
    become: yes
    apt:
      name: openjdk-8-jre-headless
      purge: yes
      state: absent

  - name: Install Oracle Java 8
    become: yes
    apt: name={{item}} state=latest
    with_items:
      - ca-certificates
      - openjdk-8-jre-headless